"""'Init'

Revision ID: 521f9985cbf4
Revises: 8f8588b3e587
Create Date: 2023-07-27 17:30:56.869720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521f9985cbf4'
down_revision = '8f8588b3e587'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
