"""Add shared column to pictures table

Revision ID: 7c5085e3c193
Revises: 9ab9c36a0300
Create Date: 2023-07-30 11:56:58.240999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5085e3c193'
down_revision = '9ab9c36a0300'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('shared', sa.Boolean(), nullable=True))
    op.drop_constraint('pic_trans_url_uniq', 'transformed_pictures', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('pic_trans_url_uniq', 'transformed_pictures', ['picture_id', 'url'])
    op.drop_column('pictures', 'shared')
    # ### end Alembic commands ###
