"""'Init'

Revision ID: 8f8588b3e587
Revises: 143aeb6fe5c6
Create Date: 2023-07-26 17:46:46.376872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8588b3e587'
down_revision = '143aeb6fe5c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('comments', sa.Column('edited', sa.Boolean(), nullable=True))
    op.add_column('comments', sa.Column('edited_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'edited_at')
    op.drop_column('comments', 'edited')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
