"""Uniq constraints

Revision ID: 9ab9c36a0300
Revises: e4709d56ec78
Create Date: 2023-07-30 02:19:59.463960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab9c36a0300'
down_revision = 'e4709d56ec78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('picture_m2m_tag', 'picture_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('picture_m2m_tag', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('pic_tag_uniq', 'picture_m2m_tag', ['picture_id', 'tag_id'])
    op.drop_column('picture_m2m_tag', 'id')
    op.drop_index('ix_pictures_id', table_name='pictures')
    op.alter_column('transformed_pictures', 'picture_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('pic_trans_url_uniq', 'transformed_pictures', ['picture_id', 'url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pic_trans_url_uniq', 'transformed_pictures', type_='unique')
    op.alter_column('transformed_pictures', 'picture_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('ix_pictures_id', 'pictures', ['id'], unique=False)
    op.add_column('picture_m2m_tag', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('pic_tag_uniq', 'picture_m2m_tag', type_='unique')
    op.alter_column('picture_m2m_tag', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('picture_m2m_tag', 'picture_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
