"""Sharet

Revision ID: e5761b6b1d36
Revises: e4709d56ec78
Create Date: 2023-07-29 22:48:22.198688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5761b6b1d36'
down_revision = 'e4709d56ec78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_1', 'picture_m2m_tag', ['picture_id', 'tag_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_1', 'picture_m2m_tag', type_='unique')
    # ### end Alembic commands ###
